UserManagementSystem/UserManagementSystem/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'))
]

UserManagementSystem/users/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.urls import path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    # path('', RedirectView.as_view(url=reverse_lazy('admin:index'))),
    path('', views.base, name='base'),
    path('register/', views.index, name='register'),
    path('login/', views.user_login, name='login'),
    path('home/', views.home, name='home'),
    path('logout/', views.user_logout, name='logout'),
    path('changepass/', views.change_pass, name='changepass'),
    path('changepwd/', views.change_pwd, name='changepwd'),
    path('userdetail/<int:id>', views.user_detail, name='detail'),
    path('show/', views.user_display, name='show'),
    path('profile/', views.edit_profile, name='profile'),
    path('delete/<int:id>', views.user_delete, name='deleteuser'),
    path('<int:id>', views.user_edit, name='edituser'),
    path('add/', views.user_add, name='adduser'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='forgotpassword/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='forgotpassword/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='forgotpassword/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='forgotpassword/password_reset_complete.html'), name='password_reset_complete'),
    path('addpost/', views.add_post, name='addpost'),
    path('editpost/<int:id>', views.edit_post, name='editpost'),
    path('delpost/<int:id>', views.delete_post, name='delpost'),
]

UserManagementSystem/users/models.py
from django.db import models
from django.core import validators

class Blog(models.Model):
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=200)


class ShowUser(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)


class MyModel:
    pass

UserManagementSystem/users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms

from .models import Blog


class SignUpForm(UserCreationForm):
    fullname = forms.CharField(label="Full name")

    class Meta:
        model = User
        fields = ['username', 'fullname', 'email']
        labels = {'email': 'Email', 'password2': 'Confirm Password'}



class EditUserForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'date_joined', 'last_login']
        labels = {'email': 'Email'}


class EditAdminForm(UserChangeForm):
    password = None

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'last_login', 'groups', 'user_permissions',
                  'is_superuser', 'is_active', 'date_joined']
        labels = {'email': 'Email'}


class UpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'is_superuser', 'groups', 'user_permissions']
        labels = {'email': 'Email'}


class PostForm(forms.ModelForm):
    title = forms.CharField(widget=forms.Textarea(attrs={'cols': 90, 'rows': 1}))
    desc = forms.CharField(label='Description', widget=forms.Textarea(attrs={'cols': 90, 'rows': 8}))

    class Meta:
        model = Blog
        fields = ['title', 'desc']

UserManagementSystem/users/views.py
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.forms import UserCreationForm
from django.core.mail import send_mail
from django.template.loader import render_to_string
from .forms import EditUserForm, EditAdminForm, UpdateForm, SignUpForm, PostForm
from django.contrib.auth.models import User, Group
from django.shortcuts import render, HttpResponseRedirect
from django.db import IntegrityError
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, SetPasswordForm
from django.conf import settings
from django.contrib import messages
from django.core.mail import EmailMessage
from .models import Blog


def home(request):
    if request.user.is_authenticated:
        posts = Blog.objects.all()
        if request.method == "POST":
            if request.user.is_superuser == True:
                f = EditAdminForm(request.POST, instance=request.user)
                users = User.objects.all()

            else:
                f = EditUserForm(request.POST, instance=request.user)
                users = None
            if f.is_valid():
                messages.success(request, 'Your Profile is updated')
                f.save()

        else:
            if request.user.is_superuser == True:
                f = EditAdminForm(instance=request.user)
                users = User.objects.all()
            else:
                f = EditUserForm(instance=request.user)
                users = None
        return render(request, 'home.html', {'name': request.user.username, 'form': f, 'users': users, 'posts': posts})
    else:
        return HttpResponseRedirect('/login/')


def user_permission(request):
    if request.user.is_authenticated:
        users = User.objects.all()
        return render(request, 'home.html', {'name': request.user.username}, {'users': users})
    else:
        return HttpResponseRedirect('/login/')


def base(request):
    return render(request, 'base.html')


def index(request):
    if request.method == 'POST':
        f = SignUpForm(request.POST)
        if f.is_valid():
            user = f.save()
            group = Group.objects.get(name='User')
            user.groups.add(group)
            html_template = 'registration/email.html'
            html_message = render_to_string(html_template, {'name': request.POST.get('username'),
                                                            'fullname': request.POST.get('fullname'),
                                                            'email': request.POST.get('email'),
                                                            })
            subject = 'You have successfully registered to User Management System'
            email_from = settings.EMAIL_HOST_USER
            to_list = [User.email, settings.EMAIL_HOST_USER]
            message = EmailMessage(subject, html_message, email_from, to_list)
            message.content_subtype = "html"
            message.send()
            messages.success(request, 'Congratulations! Your account is created successfully')
    else:
        f = SignUpForm()
    return render(request, 'registration/register.html', {"form": f})


def user_login(request):
    if not request.user.is_authenticated:
        if request.method == 'POST':
            f = AuthenticationForm(request=request, data=request.POST)
            if f.is_valid():
                username = request.POST['username']
                password = request.POST['password']
                user = authenticate(request, username=username, password=password)
                if user is not None:
                    login(request, user)
                    messages.success(request, 'Logged in successfully')
                    return HttpResponseRedirect('/home/')
        else:
            f = UserCreationForm(request.POST)
            f = AuthenticationForm()
        return render(request, 'registration/login.html', {'form': f})
    else:
        return HttpResponseRedirect('/home/')


def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/login/')


def change_pass(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            f = PasswordChangeForm(user=request.user, data=request.POST)
            if f.is_valid():
                f.save()
                update_session_auth_hash(request, f.user)
                messages.success(request, 'Your password is changed successfully')
                return HttpResponseRedirect('/home')
        else:
            f = PasswordChangeForm(user=request.user)
        return render(request, 'registration/changepass.html', {'form': f})

    else:
        return HttpResponseRedirect('/login/')


def change_pwd(request):
    if request.method == 'POST':
        f = SetPasswordForm(user=request.user, data=request.POST)
        if f.is_valid():
            f.save()
            update_session_auth_hash(request, f.user)
            messages.success(request, 'Your password is changed successfully')
            return HttpResponseRedirect('/home')
    else:
        f = SetPasswordForm(user=request.user)
    return render(request, 'registration/changepwd.html', {'form': f})


def user_detail(request, id):
    if request.user.is_authenticated:
        pi = User.objects.get(pk=id)
        f = EditAdminForm(instance=pi)
        return render(request, 'admin/detail.html', {'form': f})
    else:
        return HttpResponseRedirect('/login')


def user_display(request):
    from .models import ShowUser
    show = User.objects.all()
    return render(request, 'admin/showuser.html', {'ShowUser': show})


def user_edit(request, id):
    if request.method == 'POST':
        pi = User.objects.get(pk=id)
        f = UpdateForm(request.POST, instance=pi)
        if f.is_valid():
            f.save()
            messages.success(request, 'The user is updated successfully')
            return HttpResponseRedirect('/show/')
    else:
        pi = User.objects.get(pk=id)
        f = UpdateForm(instance=pi)
    return render(request, 'admin/edituser.html', {'form': f})


def user_delete(request, id):
    if request.method == "POST":
        pi = User.objects.get(pk=id)
        pi.delete()
        messages.success(request, 'The user is deleted successfully')
        return HttpResponseRedirect('/show/')


def user_add(request):
    if request.method == 'POST':
        f = UpdateForm(request.POST)
        if f.is_valid():
            f.save()
            messages.success(request, 'The user is added successfully')
            return HttpResponseRedirect('/show/')
    else:
        f = UpdateForm()
    return render(request, 'admin/adduser.html', {'form': f})


def add_post(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = PostForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data['title']
                desc = form.cleaned_data['desc']
                post = Blog(title=title, desc=desc)
                post.save()
                messages.success(request, 'Post is added succesfully')
                return HttpResponseRedirect('/home/')
                form = PostForm
        else:
            form = PostForm()
        return render(request, 'blog/addpost.html', {'form': form})
    else:
        return HttpResponseRedirect('/login/')


def edit_post(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            pi = Blog.objects.get(pk=id)
            form = PostForm(request.POST, instance=pi)
            if form.is_valid():
                form.save()
                messages.success(request, 'Post is successfully updated')
                return HttpResponseRedirect('/home/')
        else:
            pi = Blog.objects.get(pk=id)
            form = PostForm(instance=pi)
        return render(request, 'blog/editpost.html', {'form': form})
    else:
        return HttpResponseRedirect('/login/')


def delete_post(request, id):
    if request.user.is_authenticated:
        if request.method == 'POST':
            pi = Blog.objects.get(pk=id)
            pi.delete()
            messages.success(request, 'Deleted Successfully')
            return HttpResponseRedirect('/home/')
    else:
        return HttpResponseRedirect('/login/')


def edit_profile(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            if request.user.is_superuser == True:
                f = EditAdminForm(request.POST, instance=request.user)
                users = User.objects.all()

            else:
                f = EditUserForm(request.POST, instance=request.user)
                users = None
            if f.is_valid():
                messages.success(request, 'Your profile is updated successfully')
                f.save()

        else:
            if request.user.is_superuser == True:
                f = EditAdminForm(instance=request.user)
                users = User.objects.all()
            else:
                f = EditUserForm(instance=request.user)
                users = None
        return render(request, 'registration/editprofile.html',
                      {'name': request.user.username, 'form': f, 'users': users})
    else:
        return HttpResponseRedirect('/login/')

UserManagementSystem/users/templates/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link href="{% static 'css/bootstrap.css' %}">
    <style>
    body{
	background: #383a3d;
	padding-top: 18vh;
}

form{
	background: #fff;
}

.form-container{
	border-radius: 10px;
	padding: 28px;
}
btn{
font-family:sans-serif;
font-weight:bold;
font-size:20px;
}

.Error{
    color:red;
}
<!--body-->
<!--{-->
<!--background-image: url("")-->
<!--}-->

h1{
color:white;
 position: absolute;
  right: 420px;
  top: 70px;
}

a {
  color: blue;
}


    </style>

</head>
<body>
{% block content %}
    <h1 class="text-center" >USER MANAGEMENT SYSTEM</h1><br><br>

<div>

    <section class="row justify-content-center">
        <section class="col-12 col-sm-6 col-md-4">

            <form method="POST" class="form-container"><br>
                {% csrf_token %}

                <a href="{% url 'register' %}" class="btn btn-primary btn-lg w-100 border border-dark">Sign
                    Up</a><br><br>
                <a href="{% url 'login' %}" class="btn btn-primary btn-lg w-100 border border-dark">Login</a><br><br>


            </form>
        </section>
    </section>
</div>

<script src="{% static 'users/js/jquery.js' %}"></script>
<script src="{% static 'users/js/popper.js' %}"></script>
<script src="{% static 'users/js/bootstrap.js' %}"></script>
<script src="{% static 'users/js/bootstrap.min.js' %}"></script>
{% endblock %}
</body>
</html>

UserManagementSystem/users/templates/home.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Home Page</title>
    <style>


    a:hover {
      color: black;
     };
    .btn{
font-weight:bold; position: absolute; left: 650px; width:100px;
    }



    </style>
</head>
<body>
{% block content %}
<nav class="navbar navbar-expand-md py-0 navbar-dark bg-dark">
    <p class="navbar-brand mb-2 mx-2 navbar-text text-right py-1 ms-3 lead">Hello, {{request.user.username}}</p>
    <ul class="navbar-nav ms-auto">
        <li class="nav-item" style="list-style: none;">
            <a class="btn btn-light btn-sm text-dark" href="{% url 'profile' %}">Edit Profile</a>
            {% if users != None%}
            <a class="btn btn-light btn-sm text-dark" href="{% url 'show' %}">Manage Users</a>
            {% endif %}
            <a class="btn btn-light btn-sm text-dark" href="{% url 'changepwd' %}">Change Password</a>
            <a class="btn btn-link text-white" href="{% url 'logout' %}">Logout</a>
        </li>
    </ul>
</nav>

{% if messages %}
<div class="alert alert-success h5 py-1 w-100">

    {% for message in messages %}
    <small {% if message.tags %} class="{{message.tags}}" {% endif %}> {{message}} </small>
    {% endfor %}

    {% endif %}
</div>
<div class="container">
<h2 class="display-4 text-weight-bold mt-2 ">
    Welcome to User Management System {{name}}</h2>
<br><br>

    <a href="{% url 'addpost' %}" class="btn btn-success text-white btn-md">Add New Post</a><br><br>

{% for post in posts%}
<div class="container border border-primary bg-dark text-white ">

    <h1 class="display-4">{{post.title}}</h1>
    <p class="lead">{{post.desc}}</p><br>

    <a href="{% url 'editpost' post.id %}" class="btn btn-light btn-md">Edit</a>
    {% if perms.users.delete_blog%}
    <form action="{% url 'delpost' post.id %}" method="POST" class="d-inline">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger btn-md">Delete</button>
    </form>
    {% endif %}<br><br>
</div>
<br>
{% endfor %}


    {% if users != None%}
    <h5 class="text-weight-bold">Hello Admin! Here is a list of all users. You can view their information by
        clicking on them.</h5>
    {% for user in users %}
    <a class="text-dark " href="{% url 'detail' user.id %}">{{user.username}}</a><br>
    {% endfor %}

    {% endif %}

        </div>

{% endblock %}
</body>
</html>